language: cpp
env:
  global:
  - FORCE_INSTALL=1

matrix:
  include:
  - os: osx
    name: "Build"
    osx_image: xcode10.2
    compiler: clang

    script:
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl
    - "./macbuild.tool"

  - os: osx
    name: "Build"
    osx_image: xcode11.3
    compiler: clang

    script:
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl
    - "./macbuild.tool"
